# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/infrared_cancer',
                'doc_host': 'https://.github.io',
                'git_url': 'https://github.com//infrared_cancer',
                'lib_path': 'infrared_cancer'},
  'syms': { 'infrared_cancer.core': { 'infrared_cancer.core.foo': ( 'https://.github.io/core.html#foo',
                                                                    'https://github.com//infrared_cancer/blob/master/infrared_cancer/core.py#L7')}}}